// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: withdraw.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asset   string `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	Network string `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
}

func (x *DepositAddressReq) Reset() {
	*x = DepositAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAddressReq) ProtoMessage() {}

func (x *DepositAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAddressReq.ProtoReflect.Descriptor instead.
func (*DepositAddressReq) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *DepositAddressReq) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *DepositAddressReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type DepositAddressRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *DepositAddressRes) Reset() {
	*x = DepositAddressRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAddressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAddressRes) ProtoMessage() {}

func (x *DepositAddressRes) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAddressRes.ProtoReflect.Descriptor instead.
func (*DepositAddressRes) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *DepositAddressRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_withdraw_proto protoreflect.FileDescriptor

var file_withdraw_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x22, 0x43, 0x0a,
	0x11, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x22, 0x2d, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x32, 0x69, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x55, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x3b, 0x70, 0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_withdraw_proto_rawDescOnce sync.Once
	file_withdraw_proto_rawDescData = file_withdraw_proto_rawDesc
)

func file_withdraw_proto_rawDescGZIP() []byte {
	file_withdraw_proto_rawDescOnce.Do(func() {
		file_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(file_withdraw_proto_rawDescData)
	})
	return file_withdraw_proto_rawDescData
}

var file_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_withdraw_proto_goTypes = []interface{}{
	(*DepositAddressReq)(nil), // 0: chainerGrpc.DepositAddressReq
	(*DepositAddressRes)(nil), // 1: chainerGrpc.DepositAddressRes
}
var file_withdraw_proto_depIdxs = []int32{
	0, // 0: chainerGrpc.AddressGenerator.GetDepositAddress:input_type -> chainerGrpc.DepositAddressReq
	1, // 1: chainerGrpc.AddressGenerator.GetDepositAddress:output_type -> chainerGrpc.DepositAddressRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_withdraw_proto_init() }
func file_withdraw_proto_init() {
	if File_withdraw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_withdraw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAddressRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_withdraw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_withdraw_proto_goTypes,
		DependencyIndexes: file_withdraw_proto_depIdxs,
		MessageInfos:      file_withdraw_proto_msgTypes,
	}.Build()
	File_withdraw_proto = out.File
	file_withdraw_proto_rawDesc = nil
	file_withdraw_proto_goTypes = nil
	file_withdraw_proto_depIdxs = nil
}
